import { z } from "zod";

export const currencySchema = z.enum(["USD", "GBP", "EUR", "AUD", "CAD", "SGD", "INR"]);
export const paymentTermsSchema = z.enum(["Net 15", "Net 30", "Net 45"]);
export const workModeSchema = z.enum(["Remote", "Hybrid", "Onsite"]);

export const employerOnboardingSchema = z.object({
  company_name: z.string().trim().min(2),
  trading_name: z.string().trim().optional().nullable(),
  country: z.string().trim().min(2),
  registration_number: z.string().trim().min(2),
  registration_type: z.string().trim().optional().nullable(),
  website: z.string().trim().url(),
  industry: z.string().trim().min(2),
  employee_count: z.coerce.number().int().nonnegative().optional().nullable(),
  primary_name: z.string().trim().min(2),
  primary_designation: z.string().trim().optional().nullable(),
  primary_email: z.string().trim().email(),
  primary_phone: z.string().trim().optional().nullable(),
  primary_timezone: z.string().trim().min(2),
  signatory_same_as_primary: z.boolean().default(false),
  signatory_name: z.string().trim().optional().nullable(),
  signatory_designation: z.string().trim().optional().nullable(),
  signatory_email: z.string().trim().email().optional().nullable(),
  signatory_phone: z.string().trim().optional().nullable(),
  billing_contact_name: z.string().trim().min(2),
  billing_contact_email: z.string().trim().email(),
  billing_contact_phone: z.string().trim().optional().nullable(),
  accounts_email: z.string().trim().email().optional().nullable(),
  currency: currencySchema,
  payment_terms: paymentTermsSchema,
  working_hours: z.string().trim().min(2),
  notice_period: z.string().trim().min(2),
  probation_period: z.string().trim().min(2),
  leave_policy: z.string().trim().min(2),
  work_mode: workModeSchema,
  nda_required: z.boolean().default(false),
  background_check_required: z.boolean().default(false),
  equipment_required: z.boolean().default(false),
  handles_customer_data: z.boolean().default(false),
});

export const employeeOnboardingSchema = z.object({
  full_name: z.string().trim().min(2),
  father_name: z.string().trim().min(2),
  date_of_birth: z.string().trim().min(1),
  gender: z.string().trim().min(1),
  email: z.string().trim().email(),
  phone: z.string().trim().min(6),
  alternate_phone: z.string().trim().optional().nullable(),
  linkedin_url: z.string().trim().url().optional().or(z.literal("")).nullable(),
  github_url: z.string().trim().url().optional().or(z.literal("")).nullable(),
  portfolio_url: z.string().trim().url().optional().or(z.literal("")).nullable(),
  current_address: z.string().trim().min(5),
  permanent_address: z.string().trim().min(5),
  state: z.string().trim().min(2),
  city: z.string().trim().min(2),
  postal_code: z.string().trim().min(4),
  emergency_contact_name: z.string().trim().min(2),
  emergency_relationship: z.string().trim().min(2),
  emergency_phone: z.string().trim().min(6),
  aadhaar_number: z.string().trim().min(8),
  pan_number: z.string().trim().min(6),
  passport_number: z.string().trim().optional().nullable(),
  account_holder_name: z.string().trim().min(2),
  account_number: z.string().trim().min(4),
  ifsc_code: z.string().trim().min(4),
  bank_name: z.string().trim().min(2),
  branch_name: z.string().trim().optional().nullable(),
  qualification: z.string().trim().min(2),
  institution: z.string().trim().min(2),
  year_of_passing: z.coerce.number().int().min(1950).max(2100),
  is_fresher: z.boolean().default(true),
  total_experience: z.string().trim().optional().nullable(),
  previous_company: z.string().trim().optional().nullable(),
  previous_designation: z.string().trim().optional().nullable(),
});

export const customFieldSchema = z.object({
  target_type: z.enum(["employee", "employer"]),
  field_label: z.string().trim().min(2),
  field_key: z.string().trim().regex(/^[a-z0-9_]+$/),
  field_type: z.enum([
    "text",
    "textarea",
    "number",
    "email",
    "phone",
    "url",
    "date",
    "dropdown",
    "multi_select",
    "checkbox",
    "file_upload",
  ]),
  required: z.boolean().default(false),
  active: z.boolean().default(true),
  placeholder: z.string().trim().optional().nullable(),
  help_text: z.string().trim().optional().nullable(),
  default_value: z.string().trim().optional().nullable(),
  options: z.string().trim().optional().nullable(),
});

export const templateSchema = z.object({
  company_id: z.string().uuid().optional().nullable(),
  template_type: z.enum(["offer_letter", "employment_agreement", "nda", "policy_document", "custom_template"]),
  template_name: z.string().trim().min(2),
  file_path: z.string().trim().min(2),
});
